export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../accets/images/svg1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../accets/images/svg2.svg'),
    alt: 'PiggyBank',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Join Our Team',
    headline: 'Creating an account is extremely easy',
    description: 'Get everything set up and ready in under 10 minutes. All you need to do is add yout information and you\'re ready to go.',
    buttonLabel: 'Start Now',
    imgStart: true,
    img: require('../../accets/images/svg3.svg'),
    alt: 'Paper',
    dark: false,
    primary: false,
    darkText: true,
}